### Options
OPTIONS http://localhost:3123

### Healthcheck
GET http://localhost:3123/main/healthcheck

###
GET http://localhost:3123/users/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZTAwNjkzMGU1ZDM5NGE5NjI3NWIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDU5NDA1MDgsImV4cCI6MTc0NTk0NDEwOH0.rINcvA84BJmNs6W3IFcvGGOqWq8hvDp8N1xUGQ6e1A8
### Create  User
POST http://localhost:3123/auth/register
Content-Type: application/json

{
  "userName": "george",
  "name": "George",
  "email": "george@example.com",
  "password": "securepassword",
  "role": "user",
  "contact": "1234567890",
  "address": "123 Admin Street"
}

### Login as Admin User
POST http://localhost:3123/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "newpassword"
}

### Admin logout
POST http://localhost:3123/auth/logout

### Check authentication
GET http://localhost:3123/auth/check-auth
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZTAwNjkzMGU1ZDM5NGE5NjI3NWIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDYwOTIzNTAsImV4cCI6MTc0NjQ0ODc1MH0.XowyZ3AgR2E_sVgSDyMksq6me23NvVuKMfSjCkavnh4

### Admin get all users
GET http://localhost:3123/admin/users

### Create user
POST http://localhost:3123/admin/users
Content-Type: application/json

{
  "userName": "george",
  "name": "George",
  "email": "example@gmail.com",
  "password": "securepassword"
}

### Admin get all users paginated
GET http://localhost:3123/admin/users?page=1&limit=2&

### Admin get all users paginated with search
GET http://localhost:3123/admin/users?page=1&limit=2&search=george


### Admin get user by id 
GET http://localhost:3123/admin/users/6810e006930e5d394a96275b

### Admin update user
PATCH  http://localhost:3123/admin/users/6810e006930e5d394a96275b
Content-Type: application/json

{
  "name": "Admin",
  "password": "newpassword"
}

### Admin delete user
DELETE  http://localhost:3123/admin/users/6811e529c54307a90c238bec







### Get Movies
GET http://localhost:3123/admin/movies

### Update Movie
PATCH http://localhost:3123/admin/movies/6814c671c1d5ea76132b8624
Content-Type: application/json

{
  "title": "Updated Movie Title",
  "duration": 155,
  "pgRating": "PG",
  "genre": "Action",
  "year": 2024,
  "director": "New Director",
  "cast": [
    {
      "name": "Actor 1",
      "role": "Lead"
    },
    {
      "name": "Actor 2",
      "role": "Supporting"
    }
  ],
  "description": "A thrilling updated description.",
  "imgURL": "https://example.com/new-image.jpg"
}

### Delete Movie
DELETE http://localhost:3123/admin/movies/6814c671c1d5ea76132b8621


### get cinemas
GET http://localhost:3123/admin/cinemas
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEwZTAwNjkzMGU1ZDM5NGE5NjI3NWIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDY4NzE3MTIsImV4cCI6MTc0NzIyODExMn0._XVsUB3L0llrvuxa7_E8vsUetmJZWyU5ddinBmtuTUY

### Get Cinema by ID
GET http://localhost:3123/admin/cinemas/68207e09ddb4d49f740049b6

### Get Halls by Cinema Id
GET http://localhost:3123/admin/cinemas/68207e09ddb4d49f740049b6/halls