POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "password": "password123",
    "role": "user",
    "contact": "1234567890",
    "address": "123 Main St",
    "geolocation": {
        "lat": 40.7128,
        "lng": -74.0060
    }
}

POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "password123"
}